### ISSUE TITLE
emscripten version？

### ISSUE THREAD

**Issue by 382303784** [1p6/supercop.js#4]
What version of emscripten are you using?

**Comment by 382303784** [comment]
I am running:
```
node index.js
```
have encountered some trouble:
```
E:\work\czr-remix-ide\ed25519\supercop.js\lib.js:130
      throw ex;
      ^

TypeError: Cannot read property 'apply' of undefined
    at Object.Module._malloc (E:\work\czr-remix-ide\ed25519\supercop.js\lib.js:1745:37)
    at Object.exports.createKeyPair (E:\work\czr-remix-ide\ed25519\supercop.js\index.js:12:24)
    at Test.<anonymous> (E:\work\czr-remix-ide\ed25519\supercop.js\test\index.js:11:18)
    at Test.bound [as _cb] (E:\work\czr-remix-ide\ed25519\supercop.js\node_modules\tape\lib\test.js:77:32)
    at Test.run (E:\work\czr-remix-ide\ed25519\supercop.js\node_modules\tape\lib\test.js:93:10)
    at Test.bound [as run] (E:\work\czr-remix-ide\ed25519\supercop.js\node_modules\tape\lib\test.js:77:32)
    at Immediate.next (E:\work\czr-remix-ide\ed25519\supercop.js\node_modules\tape\lib\results.js:81:19)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
Help me!please.

Before that, I ran:
```
npm i
npm run vendor
npm run build
```
There is my environment:
```
ubuntu:16.04
node:8.15.0
emscripten:1.38.40
```

**Comment by 1p6** [comment]
A better, working version was made by @nazar-pc, I'd recommend checking it out.
I added a link to it in this commit: https://github.com/1p6/supercop.js/commit/f19dd42e509676ec530e7f12daf2bd9dd9b50da8

**Comment by 382303784** [comment]
Thank you!I see.
